name: Lint python with Ruff

on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          python-version: '3.12'
          
      - run: uv sync
      - run: uv run ruff check . --select "E,F,I"
      - run: uv run ruff format --check .